// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.lyndon.sharkdb.helloworld.proto;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"\034\n\014HelloR" +
      "equest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007me" +
      "ssage\030\001 \001(\t\":\n\017StudentResponse\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"K\n\023Stude" +
      "ntResponseList\0224\n\017studentResponse\030\001 \003(\0132" +
      "\033.helloworld.StudentResponse\"$\n\rStreamRe" +
      "quest\022\023\n\013requestInfo\030\001 \001(\t\"&\n\016StreamResp" +
      "onse\022\024\n\014responseInfo\030\001 \001(\t2\360\002\n\007Greeter\022>" +
      "\n\010SayHello\022\030.helloworld.HelloRequest\032\026.h" +
      "elloworld.HelloReply\"\000\022C\n\rSayHelloAgain\022" +
      "\030.helloworld.HelloRequest\032\026.helloworld.H" +
      "elloReply\"\000\022K\n\016SayListMessage\022\030.hellowor" +
      "ld.HelloRequest\032\033.helloworld.StudentResp" +
      "onse\"\0000\001\022M\n\014SayHelloList\022\030.helloworld.He" +
      "lloRequest\032\037.helloworld.StudentResponseL" +
      "ist\"\000(\001\022D\n\006BiTalk\022\031.helloworld.StreamReq" +
      "uest\032\031.helloworld.StreamRequest\"\000(\0010\001B>\n" +
      "#com.lyndon.sharkdb.helloworld.protoB\017He" +
      "lloWorldProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_helloworld_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_helloworld_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_helloworld_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_helloworld_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helloworld_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
