// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.lyndon.sharkdb.helloworld.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseInfo = 1;</code>
   * @return The responseInfo.
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string responseInfo = 1;</code>
   * @return The bytes for responseInfo.
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
