// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.lyndon.sharkdb.helloworld.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestInfo = 1;</code>
   * @return The requestInfo.
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string requestInfo = 1;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
