// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.lyndon.sharkdb.helloworld.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .helloworld.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.lyndon.sharkdb.helloworld.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .helloworld.StudentResponse studentResponse = 1;</code>
   */
  com.lyndon.sharkdb.helloworld.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .helloworld.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .helloworld.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.lyndon.sharkdb.helloworld.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .helloworld.StudentResponse studentResponse = 1;</code>
   */
  com.lyndon.sharkdb.helloworld.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
